# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbuddy', '0002_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='m2m_trips', to='travelbuddy.User'),
        ),
    ]
